version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      - go-kit
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    networks:
      - go-kit
    command: "agent"

  zipkin:
    image : openzipkin/zipkin 
    restart: always
    networks:
      - go-kit
    ports :
      - "9411:9411"

networks:
  go-kit:
    driver: bridge

